version: '3.9'
services:
  db:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - ./docker/dbdata6:/data/db
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6378:6379
    volumes:
      - ./docker/redis/data:/root/redis
      - ./docker/redis/redis.conf:/user/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASE=1
